export const adminStorageKey = "nt-admin-products-v2";
export const adminSessionKey = "nt-admin-session-v1";

export const adminCategories = [
  "Monitores",
  "Teclados",
  "Mouses",
  "Headsets",
  "Gabinetes",
  "SSDs",
  "Memórias RAM",
  "Fontes",
  "Controles",
  "Carregadores e cabos",
  "Kits e combos",
  "Acessórios gamer",
];

export const adminStatuses = ["disponível", "esgotado", "sob encomenda", "rascunho"];

export const initialAdminProducts = [
  {
    id: "monitor-lg-ultragear-32",
    name: "Monitor Gamer LG UltraGear 32 QHD 165Hz",
    slug: "monitor-gamer-lg-ultragear-32-qhd-165hz",
    category: "Monitores",
    brand: "LG",
    model: "32GN600-B",
    price: "1500",
    promoPrice: "1275",
    shortDescription: "Monitor 32 polegadas QHD com 165Hz e 1ms.",
    fullDescription: "Produto cadastrado como referência para o futuro painel administrativo.",
    mainImage: "",
    images: "",
    gallery: "",
    variations: [],
    stock: 2,
    status: "disponível",
    featured: true,
    sku: "NT-MON-LG32",
    warranty: "Consultar garantia na loja",
    internalNotes: "Produto importado do catálogo atual para protótipo.",
    updatedAt: "2026-07-07",
  },
  {
    id: "controle-xbox-series",
    name: "Controle Xbox Series X/S",
    slug: "controle-xbox-series-xs",
    category: "Controles",
    brand: "Microsoft",
    model: "Xbox Wireless Controller",
    price: "500",
    promoPrice: "425",
    shortDescription: "Controle sem fio para Xbox, PC e dispositivos compatíveis.",
    fullDescription: "Produto com variações de cor preparado para edição futura.",
    mainImage: "",
    images: "",
    gallery: "",
    variations: [
      { name: "Preto", color: "Preto", price: "500", promoPrice: "425", stock: 1, sku: "NT-CTL-XBOX-PT", image: "", active: true },
      { name: "Branco", color: "Branco", price: "500", promoPrice: "425", stock: 1, sku: "NT-CTL-XBOX-BR", image: "", active: true },
      { name: "Verde", color: "Verde", price: "500", promoPrice: "425", stock: 1, sku: "NT-CTL-XBOX-VD", image: "", active: true },
    ],
    stock: 3,
    status: "disponível",
    featured: true,
    sku: "NT-CTL-XBOX",
    warranty: "Consultar garantia na loja",
    internalNotes: "Manter variações antes de publicar no catálogo oficial.",
    updatedAt: "2026-07-07",
  },
  {
    id: "headset-mchose-v9-pro",
    name: "Headset Mchose V9 Pro",
    slug: "headset-mchose-v9-pro",
    category: "Headsets",
    brand: "Mchose",
    model: "V9 Pro",
    price: "500",
    promoPrice: "425",
    shortDescription: "Headset gamer sem fio com visual premium.",
    fullDescription: "Rascunho visual para simular edição rápida no painel.",
    mainImage: "",
    images: "",
    gallery: "",
    variations: [
      { name: "Preto", color: "Preto", price: "500", promoPrice: "425", stock: 1, sku: "NT-HDS-V9PRO-PT", image: "", active: true },
      { name: "Branco", color: "Branco", price: "500", promoPrice: "425", stock: 0, sku: "NT-HDS-V9PRO-BR", image: "", active: true },
    ],
    stock: 1,
    status: "rascunho",
    featured: false,
    sku: "NT-HDS-V9PRO",
    warranty: "Consultar garantia na loja",
    internalNotes: "Revisar fotos antes de publicar.",
    updatedAt: "2026-07-07",
  },
  {
    id: "gabinete-mancer-cv100",
    name: "Gabinete Gamer Mancer CV100",
    slug: "gabinete-gamer-mancer-cv100",
    category: "Gabinetes",
    brand: "Mancer",
    model: "CV100",
    price: "180",
    promoPrice: "153",
    shortDescription: "Gabinete gamer compacto com lateral em vidro.",
    fullDescription: "Produto preparado para controle de estoque no painel.",
    mainImage: "",
    images: "",
    gallery: "",
    variations: [
      { name: "Preto", color: "Preto", price: "180", promoPrice: "153", stock: 0, sku: "NT-GAB-CV100-PT", image: "", active: true },
      { name: "Branco", color: "Branco", price: "180", promoPrice: "153", stock: 0, sku: "NT-GAB-CV100-BR", image: "", active: true },
    ],
    stock: 0,
    status: "esgotado",
    featured: false,
    sku: "NT-GAB-CV100",
    warranty: "Consultar garantia na loja",
    internalNotes: "",
    updatedAt: "2026-07-07",
  },
];

export const adminRecentChanges = [
  "SEO institucional atualizado com dados oficiais.",
  "Categorias vazias agora exibem consulta pelo WhatsApp.",
  "Painel administrativo conectado à camada Supabase com fallback local.",
];
